### ISSUE TITLE
Not working on new grafana 3.0.1

### ISSUE THREAD

**Issue by golak** [foursquare/datasource-plugin-clouderamanager#3] opened 2016-05-18 06:55 UTC
Hello!
After release Grafana 3, this plugin isn't working
![screenshot from 2016-05-18 09-49-03](https://cloud.githubusercontent.com/assets/1150258/15349831/62c2cd2a-1cde-11e6-841f-0855308da235.png)

**Comment by Engineiro** [comment] 2016-05-18 21:52
Are there plans to make this part of the official plugin API list?
https://grafana.net/plugins

**Comment by devaudio** [comment] 2016-05-24 14:48
The official one deferred to this project. But i can confirm that this does not work in 3.0.1

Same error as above, and when trying to add queries, just gives me an un-editable text box that says {{ctrl.target.refId}} ({{ctrl.target.datasource}})

**Comment by devaudio** [comment] 2016-05-24 14:53
Or in 3.0.3

**Comment by tdyas** [comment] 2016-05-24 15:18
I haven't updated the plugin yet for Grafana v3. They changed the datasource API late in the development phase and I haven't made the corresponding changes to this plugin yet. I'll probably do so later this week as part of upgrading my company's internal Grafana instance to v3.

**Comment by tdyas** [comment] 2016-05-24 19:09
It looks like fixing that issue was easier than I expected. Fixed in https://github.com/foursquare/datasource-plugin-clouderamanager/commit/b02c7f6b3be48ae2f883303a521d7cd3827dd84e.

**Closed as completed by tdyas** 2016-05-24 19:09 UTC

**Comment by devaudio** [comment] 2016-05-25 15:44
Works fine man! Keep up the good work, and thanks again.
